/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

#include "dictionary.h"

int
main (int argc, char *argv[])
{
  GtkWidget *window;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
	if (dictionary_open ()) exit(1);
	
  window = create_main_window ();

	/* attach list */
	GtkWidget *wordlist_treeview = lookup_widget (GTK_WIDGET (window), "wordlist_treeview");
	GtkListStore *list_store = list_store = gtk_list_store_new (1, G_TYPE_STRING);
	gtk_tree_view_set_model (GTK_TREE_VIEW (wordlist_treeview), GTK_TREE_MODEL (list_store));

	GtkCellRenderer *text_renderer = gtk_cell_renderer_text_new ();
	GtkTreeViewColumn *word_column = gtk_tree_view_column_new_with_attributes ("Word List", text_renderer, "text", 0, NULL);	
	gtk_tree_view_append_column (GTK_TREE_VIEW (wordlist_treeview), word_column);

  gtk_widget_show (window);
	
  gtk_main ();
  return 0;
}

