/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GdkPixbuf *main_window_icon_pixbuf;
  GtkWidget *vbox1;
  GtkWidget *menubar;
  GtkWidget *file_menuitem;
  GtkWidget *file_menu;
  GtkWidget *quit_menuitem;
  GtkWidget *edit_menuitem;
  GtkWidget *edit_menu;
  GtkWidget *copy_menuitem;
  GtkWidget *paste_menuitem;
  GtkWidget *help_menuitem;
  GtkWidget *help_menu;
  GtkWidget *about_menuitem;
  GtkWidget *handlebox;
  GtkWidget *toolbar;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *copy_toolbutton;
  GtkWidget *paste_toolbutton;
  GtkWidget *about_toolbutton;
  GtkWidget *quit_toolbutton;
  GtkWidget *hbox1;
  GtkWidget *label;
  GtkWidget *keyword_entry;
  GtkWidget *hpaned;
  GtkWidget *output_scrolledwindow;
  GtkWidget *meaning_textview;
  GtkWidget *wordlist_scrolledwindow;
  GtkWidget *wordlist_treeview;
  GtkWidget *statusbar;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (main_window, 500, 400);
  gtk_window_set_title (GTK_WINDOW (main_window), _("GDictThai"));
  gtk_window_set_destroy_with_parent (GTK_WINDOW (main_window), TRUE);
  main_window_icon_pixbuf = create_pixbuf ("gdictthai.png");
  if (main_window_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (main_window), main_window_icon_pixbuf);
      gdk_pixbuf_unref (main_window_icon_pixbuf);
    }

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (main_window), vbox1);

  menubar = gtk_menu_bar_new ();
  gtk_widget_show (menubar);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar, FALSE, FALSE, 0);

  file_menuitem = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (file_menuitem);
  gtk_container_add (GTK_CONTAINER (menubar), file_menuitem);

  file_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file_menuitem), file_menu);

  quit_menuitem = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit_menuitem);
  gtk_container_add (GTK_CONTAINER (file_menu), quit_menuitem);

  edit_menuitem = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (edit_menuitem);
  gtk_container_add (GTK_CONTAINER (menubar), edit_menuitem);

  edit_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (edit_menuitem), edit_menu);

  copy_menuitem = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (copy_menuitem);
  gtk_container_add (GTK_CONTAINER (edit_menu), copy_menuitem);

  paste_menuitem = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_show (paste_menuitem);
  gtk_container_add (GTK_CONTAINER (edit_menu), paste_menuitem);

  help_menuitem = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (help_menuitem);
  gtk_container_add (GTK_CONTAINER (menubar), help_menuitem);

  help_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help_menuitem), help_menu);

  about_menuitem = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about_menuitem);
  gtk_container_add (GTK_CONTAINER (help_menu), about_menuitem);

  handlebox = gtk_handle_box_new ();
  gtk_widget_show (handlebox);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox, FALSE, FALSE, 0);

  toolbar = gtk_toolbar_new ();
  gtk_widget_show (toolbar);
  gtk_container_add (GTK_CONTAINER (handlebox), toolbar);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar), GTK_TOOLBAR_ICONS);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar));

  copy_toolbutton = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-copy");
  gtk_widget_show (copy_toolbutton);
  gtk_container_add (GTK_CONTAINER (toolbar), copy_toolbutton);

  paste_toolbutton = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-paste");
  gtk_widget_show (paste_toolbutton);
  gtk_container_add (GTK_CONTAINER (toolbar), paste_toolbutton);

  about_toolbutton = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-about");
  gtk_widget_show (about_toolbutton);
  gtk_container_add (GTK_CONTAINER (toolbar), about_toolbutton);

  quit_toolbutton = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-quit");
  gtk_widget_show (quit_toolbutton);
  gtk_container_add (GTK_CONTAINER (toolbar), quit_toolbutton);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, TRUE, 0);

  label = gtk_label_new (_("Word"));
  gtk_widget_show (label);
  gtk_box_pack_start (GTK_BOX (hbox1), label, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label, 50, -1);

  keyword_entry = gtk_entry_new ();
  gtk_widget_show (keyword_entry);
  gtk_box_pack_start (GTK_BOX (hbox1), keyword_entry, TRUE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (keyword_entry, GTK_CAN_DEFAULT);
  gtk_entry_set_max_length (GTK_ENTRY (keyword_entry), 20);
  gtk_entry_set_activates_default (GTK_ENTRY (keyword_entry), TRUE);

  hpaned = gtk_hpaned_new ();
  gtk_widget_show (hpaned);
  gtk_box_pack_start (GTK_BOX (vbox1), hpaned, TRUE, TRUE, 0);

  output_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (output_scrolledwindow);
  gtk_paned_pack1 (GTK_PANED (hpaned), output_scrolledwindow, TRUE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (output_scrolledwindow), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (output_scrolledwindow), GTK_SHADOW_IN);

  meaning_textview = gtk_text_view_new ();
  gtk_widget_show (meaning_textview);
  gtk_container_add (GTK_CONTAINER (output_scrolledwindow), meaning_textview);
  gtk_widget_set_size_request (meaning_textview, 150, -1);
  GTK_WIDGET_UNSET_FLAGS (meaning_textview, GTK_CAN_FOCUS);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (meaning_textview), FALSE);
  gtk_text_view_set_accepts_tab (GTK_TEXT_VIEW (meaning_textview), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (meaning_textview), GTK_WRAP_WORD);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (meaning_textview), FALSE);
  gtk_text_view_set_pixels_above_lines (GTK_TEXT_VIEW (meaning_textview), 5);
  gtk_text_view_set_pixels_below_lines (GTK_TEXT_VIEW (meaning_textview), 5);
  gtk_text_view_set_left_margin (GTK_TEXT_VIEW (meaning_textview), 5);
  gtk_text_view_set_right_margin (GTK_TEXT_VIEW (meaning_textview), 5);

  wordlist_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (wordlist_scrolledwindow);
  gtk_paned_pack2 (GTK_PANED (hpaned), wordlist_scrolledwindow, TRUE, FALSE);
  gtk_widget_set_size_request (wordlist_scrolledwindow, 100, -1);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (wordlist_scrolledwindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (wordlist_scrolledwindow), GTK_SHADOW_IN);

  wordlist_treeview = gtk_tree_view_new ();
  gtk_widget_show (wordlist_treeview);
  gtk_container_add (GTK_CONTAINER (wordlist_scrolledwindow), wordlist_treeview);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (wordlist_treeview), TRUE);

  statusbar = gtk_statusbar_new ();
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) main_window, "destroy",
                    G_CALLBACK (on_quit_menuitem_activate),
                    NULL);
  g_signal_connect ((gpointer) quit_menuitem, "activate",
                    G_CALLBACK (on_quit_menuitem_activate),
                    NULL);
  g_signal_connect ((gpointer) copy_menuitem, "activate",
                    G_CALLBACK (on_copy_menuitem_activate),
                    NULL);
  g_signal_connect ((gpointer) paste_menuitem, "activate",
                    G_CALLBACK (on_paste_menuitem_activate),
                    NULL);
  g_signal_connect ((gpointer) about_menuitem, "activate",
                    G_CALLBACK (on_about_menuitem_activate),
                    NULL);
  g_signal_connect ((gpointer) copy_toolbutton, "clicked",
                    G_CALLBACK (on_copy_menuitem_activate),
                    NULL);
  g_signal_connect ((gpointer) paste_toolbutton, "clicked",
                    G_CALLBACK (on_paste_menuitem_activate),
                    NULL);
  g_signal_connect ((gpointer) about_toolbutton, "clicked",
                    G_CALLBACK (on_about_menuitem_activate),
                    NULL);
  g_signal_connect ((gpointer) quit_toolbutton, "clicked",
                    G_CALLBACK (on_quit_menuitem_activate),
                    NULL);
  g_signal_connect ((gpointer) keyword_entry, "changed",
                    G_CALLBACK (on_keyword_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) wordlist_treeview, "cursor_changed",
                    G_CALLBACK (on_treeview_cursor_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, main_window, "main_window");
  GLADE_HOOKUP_OBJECT (main_window, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (main_window, menubar, "menubar");
  GLADE_HOOKUP_OBJECT (main_window, file_menuitem, "file_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, file_menu, "file_menu");
  GLADE_HOOKUP_OBJECT (main_window, quit_menuitem, "quit_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, edit_menuitem, "edit_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, edit_menu, "edit_menu");
  GLADE_HOOKUP_OBJECT (main_window, copy_menuitem, "copy_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, paste_menuitem, "paste_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, help_menuitem, "help_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, help_menu, "help_menu");
  GLADE_HOOKUP_OBJECT (main_window, about_menuitem, "about_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, handlebox, "handlebox");
  GLADE_HOOKUP_OBJECT (main_window, toolbar, "toolbar");
  GLADE_HOOKUP_OBJECT (main_window, copy_toolbutton, "copy_toolbutton");
  GLADE_HOOKUP_OBJECT (main_window, paste_toolbutton, "paste_toolbutton");
  GLADE_HOOKUP_OBJECT (main_window, about_toolbutton, "about_toolbutton");
  GLADE_HOOKUP_OBJECT (main_window, quit_toolbutton, "quit_toolbutton");
  GLADE_HOOKUP_OBJECT (main_window, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (main_window, label, "label");
  GLADE_HOOKUP_OBJECT (main_window, keyword_entry, "keyword_entry");
  GLADE_HOOKUP_OBJECT (main_window, hpaned, "hpaned");
  GLADE_HOOKUP_OBJECT (main_window, output_scrolledwindow, "output_scrolledwindow");
  GLADE_HOOKUP_OBJECT (main_window, meaning_textview, "meaning_textview");
  GLADE_HOOKUP_OBJECT (main_window, wordlist_scrolledwindow, "wordlist_scrolledwindow");
  GLADE_HOOKUP_OBJECT (main_window, wordlist_treeview, "wordlist_treeview");
  GLADE_HOOKUP_OBJECT (main_window, statusbar, "statusbar");

  gtk_widget_grab_focus (keyword_entry);
  gtk_widget_grab_default (keyword_entry);
  gtk_window_add_accel_group (GTK_WINDOW (main_window), accel_group);

  return main_window;
}

GtkWidget*
create_about_dialog (void)
{
  GtkWidget *about_dialog;
  const gchar *authors[] = {
    "Maintainer/Programmer:",
    "Kitt Tientanopajai <kitty@kitty.in.th>",
    NULL
  };
  const gchar *artists[] = {
    "Logo has been stolen from KDictThai :P",
    "KDictThai is maintained by ",
    "Thanomsub Noppaburana <donga_n@yahoo.com>",
    NULL
  };
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator-credits");
  GdkPixbuf *about_dialog_logo_pixbuf;

  about_dialog = gtk_about_dialog_new ();
  gtk_widget_set_size_request (about_dialog, 300, -1);
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (about_dialog), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (about_dialog), _("GDictThai"));
  gtk_about_dialog_set_copyright (GTK_ABOUT_DIALOG (about_dialog), _("Copyright (C) 2005 kitty.in.th\n\nMaintainer/Programmer:\nKitt Tientanopajai <kitty@kitty.in.th>"));
  gtk_about_dialog_set_comments (GTK_ABOUT_DIALOG (about_dialog), _("A GTK+ English-to-Thai Dictionary"));
  gtk_about_dialog_set_license (GTK_ABOUT_DIALOG (about_dialog), _("This program is free software; you can redistribute it and/or modify it\nunder the terms of the GNU General Public License as published by the\nFree Software Foundation; either version 2 of the License, or (at your\noption) any later version.\n\nThis program is distributed in the hope that it will be useful, but\nWITHOUT ANY WARRANTY; without even the implied warranty of\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See\nthe GNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License\nalong with this program; if not, write to the Free Software Foundation,\nInc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA"));
  gtk_about_dialog_set_website (GTK_ABOUT_DIALOG (about_dialog), "http://kitty.in.th/index.php?project=gdictthai");
  gtk_about_dialog_set_authors (GTK_ABOUT_DIALOG (about_dialog), authors);
  gtk_about_dialog_set_artists (GTK_ABOUT_DIALOG (about_dialog), artists);
  gtk_about_dialog_set_translator_credits (GTK_ABOUT_DIALOG (about_dialog), translators);
  about_dialog_logo_pixbuf = create_pixbuf ("gdictthai.svg");
  gtk_about_dialog_set_logo (GTK_ABOUT_DIALOG (about_dialog), about_dialog_logo_pixbuf);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (about_dialog, about_dialog, "about_dialog");

  return about_dialog;
}

